import os
import sys


def main():
    if len(sys.argv) != 4:
        print("Usage: generate_demo3_assets.py <count> <compose_path> <upstream_path>")
        return 1

    try:
        count = int(sys.argv[1])
    except ValueError:
        print("Count must be an integer")
        return 1

    compose_path = sys.argv[2]
    upstream_path = sys.argv[3]

    os.makedirs(os.path.dirname(compose_path) or ".", exist_ok=True)
    os.makedirs(os.path.dirname(upstream_path) or ".", exist_ok=True)

    # Generate nginx upstream config
    upstream_lines = ["upstream backend-lb {"]
    for i in range(1, count + 1):
        upstream_lines.append(f"    server backend-{i}:5000 weight=1;")
    upstream_lines.append("}")

    with open(upstream_path, "w", encoding="utf-8") as f:
        f.write("\n".join(upstream_lines))

    # Generate docker-compose.yml
    lines = []
    lines.append("# Generated by task prepare. Edit Taskfile BACKENDS and rerun prepare to change backend count.")
    lines.append("services:")

    for i in range(1, count + 1):
        ip = 100 + i
        lines.append(f"  backend-{i}:")
        lines.append("    build: ./backend")
        lines.append("    image: ds/demo-3/backend:0.1")
        lines.append(f"    container_name: backend-{i}")
        lines.append(f"    hostname: backend-{i}")
        lines.append("    networks:")
        lines.append("      demo3-net:")
        lines.append(f"        ipv4_address: 10.55.3.{ip}")
        lines.append("    volumes:")
        lines.append("      - ./:/vagrant")
        lines.append("    tty: true")
        lines.append("")

    lines.append("  frontend-lb:")
    lines.append("    build: ./frontend")
    lines.append("    image: ds/demo-3/frontend:0.1")
    lines.append("    container_name: frontend-lb")
    lines.append("    hostname: frontend-lb")
    lines.append("    depends_on:")
    for i in range(1, count + 1):
        lines.append(f"      - backend-{i}")
    lines.append("    environment:")
    lines.append("      STARTUP_DELAY: \"60\"")
    lines.append("    ports:")
    lines.append("      - \"8080:80\"")
    lines.append("    networks:")
    lines.append("      demo3-net:")
    lines.append("        ipv4_address: 10.55.3.10")
    lines.append("    volumes:")
    lines.append("      - ./:/vagrant")
    lines.append("    tty: true")
    lines.append("")

    lines.append("networks:")
    lines.append("  demo3-net:")
    lines.append("    name: demo-3-net")
    lines.append("    ipam:")
    lines.append("      config:")
    lines.append("        - subnet: 10.55.3.0/24")

    with open(compose_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())